version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR and getting Eidos JAR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - aws s3 cp s3://bigmech/travis/eidos-assembly-0.2.3-SNAPSHOT.jar .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --squash -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
